#!/usr/bin/env node
// skills.mjs — generate one harness SKILL.md per agent THIS vault defines.
//
//   synapse skills                     # show what would be written
//   synapse skills --write             # write <vault>/.dsh/skills/synapse-<agent>/SKILL.md
//   synapse skills --write --agent oracle
//   synapse skills --write --out ~/.dsh/skills       # the user-scoped root instead of the project one
//   synapse skills --write --force     # also overwrite hand-authored skills (destructive; see below)
//
// WHY THIS EXISTS. decision-0008 settled that "the package declares the roster; the harness consumes
// it" — a conforming harness reads the agent registry "instead of a hand-maintained list of names, so
// adding a watchable agent is a package edit, not a per-install re-wiring". Three of the four consumer
// surfaces already honour that: agents.sh eval's one verb per agents/agent-*.md, the launcher renders
// the briefing into opencode's and Cursor's native identity formats, and synapse_list_agents reads the
// same frontmatter over MCP. The DeepSeek Harness was the exception — four SKILL.md files shipped in
// the package, i.e. exactly the hand-maintained list of names decision-0008 ruled out. A vault with its
// own agents got no `/synapse-<agent>` gesture for any of them.
//
// WHY A SKILL, AND WHY THE `/name` GESTURE. note-dsh-extension-seams rejected every other seam with a
// reason: dsh-mcp-client implements tools only (no prompts/list), so the MCP server CANNOT contribute a
// slash command; presets cannot live in a project repo, are invisible when symlinked, and do not exist
// headless at all; dsh-commands results "never enter model history". The `/<name>` gesture is the only
// deterministic entry point left — it injects the skill body as user-role context with no model
// discretion, and works headless because the runner submits the task as an ordinary user message.
//
// WHY THE BODY IS A POINTER, NOT A PAYLOAD. Same note: "a skill is a fine container for a procedure but
// a poor one for a pointer", and skill bodies have no size cap, so a SKILL.md that grows toward briefing
// size re-creates the context problem the whole engine exists to solve. So the generated body carries the
// PROCEDURE (how to become this agent, how to delegate, what it must never do) and defers the PAYLOAD to
// synapse_brief, which the render engine already builds deterministically from the same frontmatter.
//
// HAND-AUTHORED WINS. A SKILL.md without our generated-marker is never overwritten without --force. The
// four skills this package ships were tuned against observed local-30B failure modes (claim conflated
// with spawn, polling a doer nobody launched, `refused: "held"` treated as fatal) and that tuning must
// not be silently flattened by a regeneration.
//
// This module is BOTH a CLI (guarded by isMain at the bottom) and a library: `synapse install` imports
// buildSkillTargets + applySkillTargets so one `synapse install --write` also wires the harness skills.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { resolveVault } from "./vault-root.mjs";

// The marker that distinguishes a generated skill from a hand-authored one. It lives in the BODY, not
// in frontmatter: DSH drops a whole skill on a malformed frontmatter value, and the invocation keys are
// already a known trap (camelCase spellings are actively rejected), so we add no keys to a block whose
// parser we do not control. An HTML comment is inert in every consumer.
export const GENERATED_MARKER = "<!-- generated by `synapse skills` — do not edit;";
const markerFor = (id) => `${GENERATED_MARKER} regenerate from agents/${id}.md. Delete this line to hand-author. -->`;

// DSH's catalog exposes names and capped descriptions ONLY — `whenToUse`, bodies, paths and providers
// are all excluded — which makes `description` the single routing signal the model ever sees. Cap the
// purpose, never the trigger sentence appended after it.
export const DEFAULT_MAX_DESCRIPTION = 480;

// DSH validates the frontmatter `name` against this and drops the skill (with a warning) when it fails.
// The catalog name is the frontmatter name, not the directory name — so an id that cannot produce a
// valid one is a hard skip, not a silent rename.
const SKILL_NAME_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

// ── frontmatter ───────────────────────────────────────────────────────────────
// Deliberately local rather than imported from mcp/vault.mjs: that module resolves its vault from the
// environment at import time (the MCP server's pinned-config contract), which is wrong for a CLI that
// must read whichever vault you are standing in. This variant also understands the INLINE array form
// (`delegates_to: ["[[agent-x]]"]`) that agent files actually use, which the MCP reader returns as a
// raw string.
export function parseAgentFrontmatter(raw) {
  const m = String(raw).match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  let key = null;
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) {
      key = kv[1];
      const v = kv[2].trim();
      out[key] = v === "" ? [] : parseScalarOrInlineList(v);
    } else if (key && /^\s*-\s+/.test(line)) {
      if (!Array.isArray(out[key])) out[key] = [];
      out[key].push(unquote(line.replace(/^\s*-\s+/, "").trim()));
    }
  }
  return out;
}

const unquote = (s) => s.replace(/^["']|["']$/g, "");

function parseScalarOrInlineList(v) {
  if (!v.startsWith("[")) return unquote(v);
  // An inline list. JSON first (agent files quote every element); fall back to a split so a
  // hand-edited `[a, b]` still yields a list rather than a nonsense string.
  try {
    const parsed = JSON.parse(v);
    if (Array.isArray(parsed)) return parsed.map((x) => String(x));
  } catch { /* fall through */ }
  return v.slice(1, v.lastIndexOf("]")).split(",").map((s) => unquote(s.trim())).filter(Boolean);
}

const asList = (v) => (Array.isArray(v) ? v : v == null || v === "" ? [] : [String(v)]);
// Frontmatter booleans arrive as strings — `addressable: true` parses to "true", not true. Same guard
// mcp/tools/agents.mjs uses; keep the two in step.
const flag = (v) => String(v).trim() === "true";
// "[[agent-reconciler]]" → "reconciler"
const shortOf = (ref) => String(ref).replace(/^\[\[|\]\]$/g, "").replace(/^agent-/, "").trim();

// ── description ───────────────────────────────────────────────────────────────
// Two passes, both load-bearing:
//   sanitize — collapse newlines and neutralise the ": " and quote sequences that turn a plain YAML
//     scalar into a mapping. We ALSO quote the emitted value (correct YAML), so this is belt-and-braces:
//     the value stays readable even under a naive line-splitting parser.
//   cap      — trim the purpose on a word boundary, then append the trigger sentence intact, so the one
//     routing signal the model gets can never be the half that got truncated.
export function sanitizeDescription(s) {
  return String(s ?? "")
    .replace(/\s*\r?\n\s*/g, " ")
    .replace(/"/g, "'")
    .replace(/:\s/g, " — ")
    .replace(/\s+/g, " ")
    .trim();
}

function capAt(s, max) {
  if (s.length <= max) return s;
  const cut = s.slice(0, max);
  const sp = cut.lastIndexOf(" ");
  return (sp > max * 0.6 ? cut.slice(0, sp) : cut).replace(/[\s,;—-]+$/, "") + "…";
}

export function buildDescription(fm, { maxDescription = DEFAULT_MAX_DESCRIPTION } = {}) {
  const short = shortOf(fm.id || "");
  const areas = asList(fm.tags).filter((t) => t.startsWith("area/")).map((t) => t.slice(5));
  const purpose = sanitizeDescription(fm.purpose || fm.title || `Act as agent-${short} in the Synapse vault.`);
  const head = capAt(purpose, maxDescription).replace(/[.\s]+$/, "");
  const trigger = `Use when a task names ${short}, agent-${short}`
    + (areas.length ? `, or concerns ${areas.join(" or ")} in the Synapse vault` : " in the Synapse vault")
    + ".";
  return `${head}. ${trigger}`;
}

// ── body ──────────────────────────────────────────────────────────────────────
// The invariant blocks below are lifted verbatim from the four hand-tuned skills this package ships,
// because every line of them was written against a failure actually observed driving a local 30B
// through the harness. Generating them keeps that tuning in ONE place instead of copy-pasted per agent.

const WORKING_ECONOMY = `## Working economy (applies to every step above)

- **Reach for vault content through the MCP tools, never the filesystem.** Fetch a note by id with
  \`synapse_brief(note: "<id>")\`; ids resolve without paths. The vault's layout is not what it looks
  like — decisions live under \`_meta/\`, records are generated views — so a guessed path fails, or worse
  returns a stale copy. Never \`read\`/\`glob\` vault content by hand.
- **Brief once per hub.** Re-briefing the same hub burns context and makes the answer worse on a local
  model. When the topic shifts, call \`synapse_recall\` for the delta instead.
- **Stop when the question is answered.** Extra tool calls are not extra diligence.`;

function delegationBlock(targets) {
  const named = targets.length
    ? `You delegate to: ${targets.map((t) => `\`${t}\``).join(", ")}.`
    : "";
  return `## Delegating

Delegation is **three separate calls**. \`synapse_claim_and_brief\` does *not* start a worker — it only
takes the lease, opens the episode, and returns the briefing. You must launch the doer yourself.
${named ? `\n${named}\n` : ""}
1. **Claim the job first.** \`mcp__synapse__synapse_claim_and_brief\` with the specialist \`agent\` and a
   canonical \`job\` id built from stable facts (e.g. \`reconciler:hub-finances:view-drift\`). Use an agent
   that exists (\`synapse_list_agents\`); never invent one, and never call \`synapse_create_agent\` just to
   have a specialist. Without a claim there is no dedup and no durable record.
2. **Launch the doer with \`run_in_background: false\`.** Call the harness's own \`subagent\` tool passing
   \`prompt\` = the briefing you just received + \`"\\n\\n---\\n\\n"\` + the task, and **\`run_in_background:
   false\`**. That argument is what makes the call WAIT and hand you the doer's answer as the tool result.
   Without it the call returns only \`started subagent <id>\` and no answer at all.
   - **Nothing spawns a worker but this call.** Do not poll \`synapse_spawn_status\` waiting for one to
     appear — that just burns the lease's TTL on a doer you never launched.
   - **Never call \`job_output\`, \`job_list\` or \`job_kill\` on a subagent id.** Subagents are not jobs; that
     lookup fails with \`unknown job <id>\`, and a failed lookup is **not** evidence the child finished.
   - **Never redo the doer's work yourself.** If the answer did not come back, release the job saying so
     and stop — a duplicated inspection costs more context than the whole delegation saved.
3. **Close it out.** \`mcp__synapse__synapse_spawn_release\` with the job/owner/token/spawnId/episodeId from
   step 1 and the doer's actual answer as the summary. An unreleased claim blocks that job for its full
   lease and loses the result from memory.

If a claim comes back \`refused: "held"\` and you are the holder, you already own that lease — reuse its
\`owner\`/\`token\` and continue at step 2 rather than re-claiming under a new job id.`;
}

export function buildBody(fm, opts = {}) {
  const short = shortOf(fm.id || "");
  const profile = String(fm.profile || "standard");
  const delegates = asList(fm.delegates_to).map(shortOf).filter(Boolean);
  const outputs = asList(fm.outputs);
  const rules = asList(fm.applies_rules).map((r) => String(r).replace(/^\[\[|\]\]$/g, ""));
  const title = String(fm.title || `Agent ${short}`);
  const heading = title.includes("—") ? title : `${short} — ${title}`;

  // Does this agent CHANGE the vault? Read it off the declared toolset rather than guessing from the
  // prose: an agent that mutates declares tool-lint (to verify) and/or tool-git (to carry a diff).
  // Handing a read-only role a "verify with lint, then log it" step is not harmless — it invites writes
  // from an agent whose whole contract is that it never makes any.
  const tools = asList(fm.uses_tools).map((t) => String(t).replace(/^\[\[|\]\]$/g, ""));
  const mutates = tools.includes("tool-lint") || tools.includes("tool-git");

  const steps = [
    `1. **Check what was already done.** \`mcp__synapse__synapse_history\` with the distinctive nouns from
   the task. Work that ran recently may already cover this, and repeating it produces a duplicate.`,
    `2. **Become this agent — ONCE.** Call \`mcp__synapse__synapse_brief\` with \`agent: "${short}"\`, exactly
   one \`hub: "hub-<domain>"\`, \`profile: "${profile}"\`, and \`task\` set to the user's request (passing
   \`task\` adds semantic recall on top of the deterministic closure). **That briefing — not this file — is
   your actual context**: it carries this role's rules, tools and typed closure, compiled from the vault.
   - **One hub, one call.** Do not re-brief and do not brief a second hub; that is what \`synapse_recall\`
     is for. Escalate to \`profile: "fat"\` only if the standard closure genuinely lacked the subject.`,
    `3. **Do the work the briefing describes**, staying inside the boundaries below.`,
  ];
  if (mutates) {
    steps.push(
      `4. **Verify.** \`mcp__synapse__synapse_lint\` — the run is done when it is clean and nothing is left
   mid-flight, not when you have run out of ideas.`,
      `5. **Record it.** \`mcp__synapse__synapse_log\` with what you changed, what you escalated, and what
   you deliberately left alone.`,
    );
  } else {
    steps.push(
      `4. **Answer**, citing the source note \`id\` for every claim. The typed closure is authoritative;
   anything returned as semantically related is a lead to verify, not a fact — say which you are using.`,
      `5. **If the topic shifts later in the session**, call \`mcp__synapse__synapse_recall\` with what you
   are doing now. It returns only the delta — never re-brief.`,
    );
  }

  const parts = [
    `---
name: synapse-${short}
description: "${buildDescription(fm, opts)}"
---`,
    markerFor(fm.id || `agent-${short}`),
    `# ${heading}`,
    String(fm.purpose || title).replace(/[.\s]*$/, "."),
    `## Procedure\n\n${steps.join("\n")}`,
  ];

  if (outputs.length) {
    parts.push(`## What you produce\n\n${outputs.map((o) => `- ${o}`).join("\n")}`);
  }
  if (delegates.length) parts.push(delegationBlock(delegates));

  const boundaries = [
    `- **Never write \`db/synapse.db\`.** Records change through a migration proposed in a PR and applied by
  a human. Never edit a \`generated: true\` view by hand — fix the source and regenerate.`,
  ];
  if (mutates) {
    boundaries.push(
      `- **Propose, do not push.** The output of a run is a reviewable diff or PR. Never self-merge, never
  force-push, never push to \`main\`. Worst case for an unattended run is a reviewable diff, never a
  silent write.`,
    );
  } else {
    boundaries.push(
      `- **Never mutate.** No \`.md\` edits, no migrations, no writes to \`db/synapse.db\`, no generated views,
  no commits, no PRs. If the vault needs a change, describe the handoff and stop — trigger one only on
  explicit human approval.`,
    );
  }
  boundaries.push(
    `- **Not in the vault? Say so.** Name what would find it (a \`fat\` profile, a different hub, an ingest)
  rather than filling the gap by inventing.`,
  );
  if (rules.length) {
    boundaries.push(
      `- **Your briefing carries the binding rules.** They are authoritative over this summary — read them
  there, and when they conflict with this file, they win:
${rules.map((r) => `  - \`${r}\``).join("\n")}`,
    );
  }
  if (flag(fm.addressable)) {
    boundaries.push(
      `- **You are addressable.** You hold a chat identity, so publish your result to the thread every
  turn — a handoff nobody can see defeats the point of having one.`,
    );
  }
  parts.push(`## Boundaries\n\n${boundaries.join("\n")}`);
  parts.push(WORKING_ECONOMY);

  return parts.join("\n\n") + "\n";
}

// ── targets ───────────────────────────────────────────────────────────────────
// Default target is the vault REPO ROOT's .dsh/skills — `root`, not `vaultDir`. DSH resolves its
// `project-dsh` root (rank 100, its highest) by walking UP from the launch cwd for a `.git` directory
// and falling back to the cwd when it finds none, so the discovered path tracks the git root. Under the
// nested layout those differ (vaultDir is root/context-vault) and writing to vaultDir would put the
// skills somewhere DSH never looks. `--out ~/.dsh/skills` targets the user-scoped root (rank 400)
// instead — what the @eborja/dsh-synapse installer symlinks; that root follows symlinks, so both
// routes coexist.
export function buildSkillTargets({ root, vaultDir, agent = null, outDir = null, maxDescription = DEFAULT_MAX_DESCRIPTION } = {}) {
  const agentsDir = join(vaultDir, "agents");
  const skillsDir = outDir || join(root, ".dsh", "skills");
  const warnings = [];
  const targets = [];

  // No .git above the target means DSH's project root falls back to whatever cwd it was launched from —
  // these skills are then discovered only when it starts here. Say so rather than let it look like a bug.
  if (!outDir && !existsSync(join(root, ".git"))) {
    warnings.push(
      `${root} is not a git repository. DSH finds its project skills by walking up for .git and falls `
      + `back to the launch directory, so these are discovered only when DSH starts in ${root}. `
      + `Use --out ~/.dsh/skills for a location that works from anywhere.`,
    );
  }

  if (!existsSync(agentsDir)) {
    warnings.push(`no agents/ directory under ${vaultDir} — nothing to generate.`);
    return { agentsDir, skillsDir, targets, warnings };
  }

  const files = readdirSync(agentsDir).filter((f) => f.startsWith("agent-") && f.endsWith(".md")).sort();
  for (const f of files) {
    const fm = parseAgentFrontmatter(readFileSync(join(agentsDir, f), "utf8"));
    const id = String(fm.id || f.replace(/\.md$/, ""));
    const short = shortOf(id);
    if (agent && short !== shortOf(agent)) continue;

    const name = `synapse-${short}`;
    if (!SKILL_NAME_RE.test(name)) {
      // DSH would drop this skill at load with only a warning; refusing here makes it visible.
      warnings.push(`${f}: "${name}" is not a valid skill name (${SKILL_NAME_RE}) — skipped.`);
      continue;
    }
    if (!fm.purpose && !fm.title) {
      warnings.push(`${f}: no purpose or title — the catalog description would be the only routing signal and it would be empty; skipped.`);
      continue;
    }
    targets.push({ id, short, name, path: join(skillsDir, name, "SKILL.md"), content: buildBody({ ...fm, id }, { maxDescription }) });
  }
  if (agent && !targets.length && !warnings.length) warnings.push(`no agent matched --agent ${agent}.`);
  return { agentsDir, skillsDir, targets, warnings };
}

// Returns one row per target describing what happened (or would happen): created | updated | unchanged
// | kept (hand-authored, needs --force) | overwritten.
export function applySkillTargets(targets, { root, write = false, force = false } = {}) {
  const results = [];
  for (const t of targets) {
    const existing = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
    const handAuthored = existing !== null && !existing.includes(GENERATED_MARKER);
    let status;
    if (existing === null) status = "created";
    else if (handAuthored) status = force ? "overwritten" : "kept";
    else status = existing === t.content ? "unchanged" : "updated";

    if (write && (status === "created" || status === "updated" || status === "overwritten")) {
      mkdirSync(join(t.path, ".."), { recursive: true });
      writeFileSync(t.path, t.content);
    }
    results.push({ ...t, status, rel: root ? relative(root, t.path) : t.path });
  }
  return results;
}

// ── CLI ───────────────────────────────────────────────────────────────────────
const ICON = { created: "+", updated: "~", overwritten: "!", unchanged: "=", kept: "·" };

function main() {
  const argv = process.argv.slice(2);
  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(`synapse skills — generate one harness SKILL.md per agent this vault defines

usage: synapse skills [--write] [--agent <id>] [--out <dir>] [--force]

  --write            write the files (default is a dry run)
  --agent <id>       only this agent (short id or agent-<id>)
  --out <dir>        target root (default <vault-repo-root>/.dsh/skills; ~/.dsh/skills works from anywhere)
  --force            also overwrite hand-authored skills (those without the generated marker)
  --max-description  cap the purpose text in the catalog description (default ${DEFAULT_MAX_DESCRIPTION})

Each agents/agent-*.md becomes /synapse-<agent> in the DeepSeek Harness. The body is a PROCEDURE that
points at synapse_brief; the briefing itself stays the payload. A SKILL.md you hand-authored is never
overwritten without --force.`);
    return;
  }
  const write = argv.includes("--write");
  const force = argv.includes("--force");
  const pick = (n, d) => { const i = argv.indexOf(`--${n}`); return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : d; };
  const agent = pick("agent", null);
  const maxDescription = Number(pick("max-description", DEFAULT_MAX_DESCRIPTION)) || DEFAULT_MAX_DESCRIPTION;
  const outRaw = pick("out", null);
  const outDir = outRaw ? outRaw.replace(/^~(?=$|\/)/, homedir()) : null;

  // preferCwd: this WRITES into a vault, so the vault you are standing in wins over a stale exported
  // $SYNAPSE_VAULT (same guard as `synapse install` and `synapse mcp-config`).
  const { root, vaultDir } = resolveVault({ preferCwd: true, readManifest: false });
  const { agentsDir, skillsDir, targets, warnings } = buildSkillTargets({ root, vaultDir, agent, outDir, maxDescription });

  console.log(`vault:  ${vaultDir}`);
  console.log(`agents: ${relative(root, agentsDir)}/`);
  console.log(`skills: ${outDir || relative(root, skillsDir) + "/"}`);
  console.log("");

  const results = applySkillTargets(targets, { root, write, force });
  for (const r of results) console.log(`  ${ICON[r.status]} ${r.status.padEnd(11)} ${("/" + r.name).padEnd(22)} ${r.rel}`);
  if (!results.length) console.log("  (nothing to generate)");

  for (const w of warnings) console.log(`\n⚠ ${w}`);
  const kept = results.filter((r) => r.status === "kept");
  if (kept.length) {
    console.log(`\n${kept.length} hand-authored skill(s) left untouched: ${kept.map((k) => k.name).join(", ")}.`);
    console.log(`Regenerate them with --force only if you mean to discard those edits.`);
  }
  const changed = results.filter((r) => ["created", "updated", "overwritten"].includes(r.status));
  if (!write) {
    console.log(`\n${changed.length} file(s) would change. Re-run with --write to apply.`);
  } else {
    console.log(changed.length
      ? `\nWrote ${changed.length} file(s). Restart the harness (or start a new session) to pick them up.`
      : `\nNothing to do.`);
  }
}

// Run the CLI only when invoked directly (synapse skills) — NOT when imported by `synapse install`.
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
